# Generated by Django 2.0.3 on 2018-04-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_class_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacherAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(db_column='class_code', on_delete=django.db.models.deletion.CASCADE, to='student.Section', unique=True)),
                ('staff', models.ForeignKey(db_column='user_name', on_delete=django.db.models.deletion.PROTECT, to='student.Staff', unique=True)),
            ],
        ),
    ]
