# Generated by Django 2.0.3 on 2018-04-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_classteacherassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacherassign',
            name='section',
            field=models.OneToOneField(db_column='class_code', on_delete=django.db.models.deletion.CASCADE, to='student.Section'),
        ),
    ]
