# Generated by Django 2.0.3 on 2018-04-07 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180407_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacherassign',
            name='staff',
            field=models.OneToOneField(db_column='user_name', on_delete=django.db.models.deletion.PROTECT, to='student.Staff'),
        ),
    ]
