# Generated by Django 2.0.3 on 2018-04-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180407_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassTeacherAssign',
            new_name='ClassTeacher',
        ),
    ]
