# Generated by Django 2.0.3 on 2018-04-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180407_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(default='', max_length=200)),
                ('section', models.ForeignKey(db_column='class_code', on_delete=django.db.models.deletion.CASCADE, to='student.Section')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnroll',
            fields=[
                ('roll_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('enroll_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
