# Generated by Django 2.0.3 on 2018-04-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_studentenroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentenroll',
            name='section',
            field=models.ForeignKey(default='', help_text='Assign Class_code', on_delete=django.db.models.deletion.CASCADE, to='student.Section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentenroll',
            name='roll_num',
            field=models.CharField(help_text='Assign Roll Number formate : YY+class_code+max_seq', max_length=20, primary_key=True, serialize=False),
        ),
    ]
