# Generated by Django 2.0.3 on 2018-04-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenroll',
            name='section',
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(db_column='class_code', default=' ', on_delete=django.db.models.deletion.CASCADE, to='student.Section'),
            preserve_default=False,
        ),
    ]
