# Generated by Django 2.0.3 on 2018-04-07 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180407_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('relation', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend_date', models.DateField(db_index=True, default=datetime.date(2018, 4, 8), verbose_name='Date')),
                ('staff', models.ForeignKey(db_column='user_name', on_delete=django.db.models.deletion.DO_NOTHING, to='student.Staff')),
                ('studentEnroll', models.ForeignKey(db_column='Roll_Num', on_delete=django.db.models.deletion.CASCADE, to='student.StudentEnroll')),
            ],
        ),
    ]
