# Generated by Django 2.0.3 on 2018-04-06 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20180406_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_type', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attend_date', models.DateField(blank=True, db_index=True, default=datetime.datetime(2018, 4, 6, 20, 21, 10, 525266))),
                ('Roll_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('user_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.Staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='class_Teacher',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.StaffType'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='class_Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Staff'),
        ),
        migrations.AddField(
            model_name='classteacher',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Section'),
        ),
    ]
