# Generated by Django 2.0.3 on 2018-04-06 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20180406_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_type',
            new_name='StaffType',
        ),
        migrations.RemoveField(
            model_name='stafftype',
            name='id',
        ),
        migrations.AlterField(
            model_name='stafftype',
            name='staff_type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='Attend_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime(2018, 4, 6, 23, 31, 9, 874641)),
        ),
    ]
