# Generated by Django 2.0.3 on 2018-04-06 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20180407_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='section',
            field=models.ForeignKey(db_column='class_code', default='Teacher', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='students.Section'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='Attend_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.datetime(2018, 4, 7, 0, 53, 27, 754820)),
        ),
        migrations.AlterUniqueTogether(
            name='classteacher',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classteacher',
            name='id',
        ),
    ]
